
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - docker pull tutum/influxdb
  - docker run -d -p 8083:8083 -p 8086:8086 --expose 8090 --expose 8099 tutum/influxdb

install:
  - pip install -r requirements.pip --use-mirrors

script:
  - nosetests -s -v
env:
  - INFLUX_HOST=127.0.0.1

