
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install ansible
  - mkdir roles
  - cd roles
  - git clone https://github.com/optimuspaul/ansible-role-influxdb
  - cd ../
  - ansible-playbook main.yml
  - pip install -r requirements.pip --use-mirrors

script:
  - nosetests -s -v
env:
  - INFLUX_HOST=127.0.0.1

