
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - wget http://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb
  - dpkg -i influxdb_latest_amd64.deb
  - service influxdb start
  - pip install -r requirements.pip --use-mirrors

script:
  - nosetests -s -v
env:
  - INFLUX_HOST=127.0.0.1

